name: warranty_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  firebase_storage: ^11.2.6
  get: ^4.6.5
  pinput: ^3.0.0
  cloud_firestore: ^4.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_form_builder: ^9.1.0
  uuid: ^3.0.7
  flutter:
    sdk: flutter
  email_validator: ^2.1.17
  form_builder_validators: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
