name: warranty_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.9.0
  convex_bottom_bar: ^3.2.0
  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  form_builder_validators: ^9.0.0
  get: ^4.6.5
  intl: ^0.18.1
  pinput: ^3.0.0
  uuid: ^3.0.7
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
