// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_GWk81_RnqxpWhSr005w4z_XfOIavqk',
    appId: '1:27847717838:web:3197d33a22fee7d4c0f19f',
    messagingSenderId: '27847717838',
    projectId: 'warranty-app-40437',
    authDomain: 'warranty-app-40437.firebaseapp.com',
    storageBucket: 'warranty-app-40437.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NreVC74LYpmdet98rLHnv0EoRvJTfPw',
    appId: '1:27847717838:android:0f786f97543da006c0f19f',
    messagingSenderId: '27847717838',
    projectId: 'warranty-app-40437',
    storageBucket: 'warranty-app-40437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAumzZsLhrSSYLNo5-N3jjiZAUUI3sj8M',
    appId: '1:27847717838:ios:3ed26bc058a53807c0f19f',
    messagingSenderId: '27847717838',
    projectId: 'warranty-app-40437',
    storageBucket: 'warranty-app-40437.appspot.com',
    iosClientId: '27847717838-je4mhtr1nroqt44mocvs944nvlf04491.apps.googleusercontent.com',
    iosBundleId: 'com.example.warrantyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAumzZsLhrSSYLNo5-N3jjiZAUUI3sj8M',
    appId: '1:27847717838:ios:2f2681a071610c41c0f19f',
    messagingSenderId: '27847717838',
    projectId: 'warranty-app-40437',
    storageBucket: 'warranty-app-40437.appspot.com',
    iosClientId: '27847717838-drnui976pkg60vcj51feh4gniaqng0gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.warrantyApp.RunnerTests',
  );
}
