// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmBFXgywW0lEvSco23t_v-pn89J7WbkGA',
    appId: '1:252765560146:web:e986750a1c75355905ae8b',
    messagingSenderId: '252765560146',
    projectId: 'warranty-app-8f644',
    authDomain: 'warranty-app-8f644.firebaseapp.com',
    storageBucket: 'warranty-app-8f644.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzdoqXREjgtEtKdKswiesr6M34Q3vfdY',
    appId: '1:252765560146:android:5f7dd656f7f126cc05ae8b',
    messagingSenderId: '252765560146',
    projectId: 'warranty-app-8f644',
    storageBucket: 'warranty-app-8f644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU1uBMExq9NPB4yzt2XqrmDkSQGiNcwrY',
    appId: '1:252765560146:ios:749536800d3a2b6005ae8b',
    messagingSenderId: '252765560146',
    projectId: 'warranty-app-8f644',
    storageBucket: 'warranty-app-8f644.appspot.com',
    iosClientId: '252765560146-b8upv72r4v7cjsopj0807m7a10talcps.apps.googleusercontent.com',
    iosBundleId: 'com.example.warrantyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU1uBMExq9NPB4yzt2XqrmDkSQGiNcwrY',
    appId: '1:252765560146:ios:5abc3cd73850631005ae8b',
    messagingSenderId: '252765560146',
    projectId: 'warranty-app-8f644',
    storageBucket: 'warranty-app-8f644.appspot.com',
    iosClientId: '252765560146-l4divoqta7j11lq8ai66dmf73n4g9c2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.warrantyApp.RunnerTests',
  );
}
